#include <catch2/catch_test_macros.hpp>

#include <cstdlib>
#include <sstream>
#include <string>
#include <vector>
#include <boost/filesystem.hpp>
#include <boost/nowide/fstream.hpp>
#include <boost/algorithm/string/predicate.hpp>

#include "libslic3r/libslic3r.h"
#include "libslic3r/Config.hpp"
#include "test_data.hpp"

using namespace Slic3r;
using namespace Slic3r::Test;

// Golden G-code comparison against the stock PrusaSlicer output.
// The reference files in tests/data/golden were generated by the untouched prusa-2.9.6 build.
// Set the environment variable PS_UPDATE_GOLDEN=1 to regenerate them.

namespace {

// Config keys added by this fork, listed in the config block at the end of the G-code.
const std::vector<std::string> added_config_keys {
    "internal_bridge_",
    "default_fan_speed", "perimeter_fan_speed", "external_perimeter_fan_speed", "overhangs_fan_speed", "infill_fan_speed",
    "solid_infill_fan_speed", "top_fan_speed", "gap_fill_fan_speed", "support_material_fan_speed", "support_material_interface_fan_speed",
    "bed_keep_out_zones",
    "gap_fill_acceleration", "support_material_acceleration", "support_material_interface_acceleration",
    "ironing_acceleration", "brim_acceleration", "brim_speed",
    "fan_speedup_time", "fan_speedup_overhangs",
    "feature_gcode",
    "small_perimeter_min_length", "small_perimeter_max_length",
    "hole_size_compensation", "hole_size_threshold",
    "avoid_crossing_not_first_layer", "avoid_crossing_top", "avoid_travel_island",
    "seam_notch_",
    "brim_ears", "brim_per_object",
    "auxiliary_fan_gcode", "additional_cooling_fan_speed",
    "solid_infill_direction", "rotate_solid_infill_direction", "align_infill_direction_to_model",
};

bool is_added_config_line(const std::string &line)
{
    for (const std::string &key : added_config_keys)
        if (boost::starts_with(line, "; " + key))
            return true;
    return false;
}

// Remove the parts of the G-code that legitimately differ from the stock output:
// the header line with date / version, the config keys added by this fork and the new
// ";TYPE:Internal bridge infill" label, which stock prints as ";TYPE:Bridge infill".
std::string normalize_gcode(const std::string &gcode)
{
    std::istringstream in(gcode);
    std::string        out;
    out.reserve(gcode.size());
    std::string line;
    while (std::getline(in, line)) {
        if (boost::starts_with(line, "; generated by") || is_added_config_line(line))
            continue;
        if (line == ";TYPE:Internal bridge infill")
            line = ";TYPE:Bridge infill";
        out += line;
        out += '\n';
    }
    return out;
}

boost::filesystem::path golden_path(const std::string &name)
{
    return boost::filesystem::path(TEST_DATA_DIR) / "golden" / (name + ".gcode");
}

std::string read_file(const boost::filesystem::path &path)
{
    boost::nowide::ifstream f(path.string(), std::ios::binary);
    return std::string((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
}

// Index of the first differing line, to make a failure readable.
std::string first_difference(const std::string &a, const std::string &b)
{
    std::istringstream ia(a), ib(b);
    std::string la, lb;
    for (size_t idx = 1;; ++ idx) {
        bool ga = bool(std::getline(ia, la));
        bool gb = bool(std::getline(ib, lb));
        if (! ga && ! gb)
            return "no difference";
        if (ga != gb || la != lb)
            return "line " + std::to_string(idx) + ": expected \"" + (gb ? lb : "<eof>") + "\" got \"" + (ga ? la : "<eof>") + "\"";
    }
}

// Settings resembling the user's Klipper profile: low base fan, high bridge fan, fan disabled on
// the first layers, per-feature accelerations, dynamic overhang fan.
DynamicPrintConfig klipper_config()
{
    return DynamicPrintConfig::full_print_config_with({
        { "gcode_flavor",                    "klipper" },
        { "use_relative_e_distances",        true },
        { "cooling",                         { 1 } },
        { "fan_always_on",                   { 1 } },
        { "min_fan_speed",                   { 30 } },
        { "max_fan_speed",                   { 35 } },
        { "bridge_fan_speed",                { 75 } },
        { "disable_fan_first_layers",        { 3 } },
        { "full_fan_speed_layer",            { 4 } },
        { "fan_below_layer_time",            { 60 } },
        { "slowdown_below_layer_time",       { 5 } },
        { "enable_dynamic_fan_speeds",       { 1 } },
        { "overhang_fan_speed_0",            { 75 } },
        { "overhang_fan_speed_1",            { 60 } },
        { "overhang_fan_speed_2",            { 45 } },
        { "overhang_fan_speed_3",            { 35 } },
        { "default_acceleration",            11000 },
        { "perimeter_acceleration",          9000 },
        { "external_perimeter_acceleration", 7000 },
        { "infill_acceleration",             11000 },
        { "solid_infill_acceleration",       10000 },
        { "top_solid_infill_acceleration",   8000 },
        { "bridge_acceleration",             5000 },
        { "first_layer_acceleration",        3000 },
        { "travel_acceleration",             11000 },
        { "bridge_speed",                    40 },
        { "fill_density",                    "15%" },
    });
}

void check_golden(const std::string &name, TestMesh mesh, const DynamicPrintConfig &config)
{
    const std::string gcode = normalize_gcode(Test::slice({ mesh }, config));
    REQUIRE(! gcode.empty());

    const boost::filesystem::path path = golden_path(name);
    const char *update = std::getenv("PS_UPDATE_GOLDEN");
    if (update != nullptr && std::string(update) == "1") {
        boost::filesystem::create_directories(path.parent_path());
        boost::nowide::ofstream f(path.string(), std::ios::binary);
        f << gcode;
        WARN("Golden G-code written: " << path.string());
        return;
    }

    REQUIRE(boost::filesystem::exists(path));
    const std::string expected = read_file(path);
    INFO(name << ": " << first_difference(gcode, expected));
    CHECK(gcode == expected);
}

} // namespace

TEST_CASE("Slicing is deterministic", "[Golden]") {
    const DynamicPrintConfig config = klipper_config();
    const std::string a = normalize_gcode(Test::slice({ TestMesh::cube_20x20x20 }, config));
    const std::string b = normalize_gcode(Test::slice({ TestMesh::cube_20x20x20 }, config));
    INFO(first_difference(a, b));
    CHECK(a == b);
}

TEST_CASE("G-code equals stock PrusaSlicer at default settings", "[Golden]") {
    const DynamicPrintConfig defaults = DynamicPrintConfig::full_print_config();
    const DynamicPrintConfig klipper  = klipper_config();

    SECTION("20mm cube, defaults")      { check_golden("cube_20mm_defaults",      TestMesh::cube_20x20x20, defaults); }
    SECTION("20mm cube, klipper")       { check_golden("cube_20mm_klipper",       TestMesh::cube_20x20x20, klipper); }
    SECTION("bridge, defaults")         { check_golden("bridge_defaults",         TestMesh::bridge,        defaults); }
    SECTION("bridge, klipper")          { check_golden("bridge_klipper",          TestMesh::bridge,        klipper); }
    SECTION("overhang, defaults")       { check_golden("overhang_defaults",       TestMesh::overhang,      defaults); }
    SECTION("overhang, klipper")        { check_golden("overhang_klipper",        TestMesh::overhang,      klipper); }
    SECTION("cube with hole, defaults") { check_golden("cube_with_hole_defaults", TestMesh::cube_with_hole, defaults); }
    SECTION("cube with hole, klipper")  { check_golden("cube_with_hole_klipper",  TestMesh::cube_with_hole, klipper); }
}
