#include <catch2/catch.hpp>

#include "perimeter_test_helpers.hpp"

namespace {
using namespace Slic3r;
using namespace Slic3r::Test::PerimeterPluginTests;

void require_default_loop_count(const PerimeterRunCapture &run, const size_t expected_count)
{
    REQUIRE(external_perimeter_count(run) == expected_count);
    REQUIRE(count_loops_with_role(external_perimeters(run), elrDefault) == expected_count);
}

void require_all_default_loops(const PerimeterRunCapture &run)
{
    const size_t count = external_perimeter_count(run);
    REQUIRE(count_loops_with_role(external_perimeters(run), elrDefault) == count);
}
}

TEST_CASE("Extra perimeter below area module extends small islands", "[plugins][perimeter]")
{
    const ExPolygon area = rectangle_expolygon(-10., -10., 10., 10.);
    const DynamicPrintConfig disabled = perimeter_config({{"extra_perimeters_below_area", "0"}});
    const DynamicPrintConfig too_small_threshold = perimeter_config({{"extra_perimeters_below_area", "1"}});
    const DynamicPrintConfig enabled = perimeter_config({{"extra_perimeters_below_area", "100000"}});

    SECTION("Disabled setting keeps only the base perimeter")
    {
        // The module should be inert when the threshold is zero. This confirms
        // that the host root traversal seed does not create hidden extra loops.
        const PerimeterRunCapture run =
            run_perimeter_case(disabled, {SIMPLE_PERIMETER_GENERATOR, EXTRA_PERIMETER_BELOW_AREA}, area, 0);
        require_default_loop_count(run, 1);
    }

    SECTION("Threshold below the first inner area is inert")
    {
        // The 20x20 mm test island still has a large inner area after the first
        // perimeter. A tiny threshold must therefore behave like the disabled
        // case and stop after the base loop.
        const PerimeterRunCapture run =
            run_perimeter_case(too_small_threshold, {SIMPLE_PERIMETER_GENERATOR, EXTRA_PERIMETER_BELOW_AREA}, area, 0);
        require_default_loop_count(run, 1);
    }

    SECTION("Large threshold keeps generating while the branch remains small enough")
    {
        // A very large threshold marks every generated child area as small. The
        // module should then request more perimeters until the simple generator
        // runs out of inner area. The exact count belongs to the generator, but
        // it must be strictly larger than the base loop and keep default roles.
        const PerimeterRunCapture run =
            run_perimeter_case(enabled, {SIMPLE_PERIMETER_GENERATOR, EXTRA_PERIMETER_BELOW_AREA}, area, 0);
        REQUIRE(external_perimeter_count(run) > 1);
        require_all_default_loops(run);
    }

    SECTION("Region-local enabled area extends only the matching branch")
    {
        // The base config disables the threshold. A left-side region
        // enables it, so the full-area base loop still crosses x=0 while every
        // extra loop generated by this module must stay in the left branch.
        const ExPolygon left_override_area = rectangle_expolygon(-9., -9., -2., 9.);
        const PerimeterRunCapture run =
            run_perimeter_case(disabled,
                               {SIMPLE_PERIMETER_GENERATOR, EXTRA_PERIMETER_BELOW_AREA},
                               area,
                               0,
                               {{"extra_perimeters_below_area", "100000"}},
                               &left_override_area);
        const size_t count = external_perimeter_count(run);
        REQUIRE(count > 1);
        require_all_default_loops(run);
        const VerticalSplitCounts split = vertical_split_counts(external_perimeters(run), 0);
        REQUIRE(split.crossing == 1);
        REQUIRE(split.left_only == count - 1);
        REQUIRE(split.right_only == 0);
    }

    SECTION("Zero base perimeter stays empty when the threshold is disabled")
    {
        // With zero base perimeters and a disabled threshold, the host traversal
        // seed must not become a real perimeter by itself.
        const DynamicPrintConfig no_base =
            perimeter_config({{"perimeters", "0"}, {"extra_perimeters_below_area", "0"}});
        const PerimeterRunCapture run =
            run_perimeter_case(no_base, {SIMPLE_PERIMETER_GENERATOR, EXTRA_PERIMETER_BELOW_AREA}, area, 0);
        require_default_loop_count(run, 0);
    }

    SECTION("Zero base perimeter does not bootstrap from the root seed")
    {
        // The simple generator may expose an inner area from the host traversal
        // seed even when perimeters=0. The below-area module must not use that
        // root seed to create the first real perimeter by itself.
        const DynamicPrintConfig no_base =
            perimeter_config({{"perimeters", "0"}, {"extra_perimeters_below_area", "100000"}});
        const PerimeterRunCapture run =
            run_perimeter_case(no_base, {SIMPLE_PERIMETER_GENERATOR, EXTRA_PERIMETER_BELOW_AREA}, area, 0);
        require_default_loop_count(run, 0);
    }

    SECTION("Zero base perimeter can extend children created by another module")
    {
        // extra_perimeters_count creates one real root perimeter even when the
        // base perimeter count is zero. Once that first loop exists, below-area
        // may extend the child areas under the threshold.
        const DynamicPrintConfig no_base_extra =
            perimeter_config({
                {"perimeters", "0"},
                {"extra_perimeters_count", "1"},
                {"extra_perimeters_below_area", "100000"}
            });
        const PerimeterRunCapture extra_only_run =
            run_perimeter_case(no_base_extra, {SIMPLE_PERIMETER_GENERATOR, EXTRA_PERIMETER_COUNT}, area, 0);
        const PerimeterRunCapture below_run =
            run_perimeter_case(no_base_extra,
                               {SIMPLE_PERIMETER_GENERATOR, EXTRA_PERIMETER_COUNT, EXTRA_PERIMETER_BELOW_AREA},
                               area,
                               0);
        REQUIRE(external_perimeter_count(extra_only_run) == 1);
        REQUIRE(external_perimeter_count(below_run) > external_perimeter_count(extra_only_run));
        require_all_default_loops(below_run);
    }
}
